'use client';
import {useResearchState} from '@/lib/use-research-state';
import type {Dataset} from '@/lib/schema';
import {channelScore,planResult} from '@/lib/analysis';
import {Evidence,NumberBars,type OpenSource} from './analytics';

export function AdGameEvidence({id,data,open}:{id:string;data:Dataset;open:OpenSource}) {
  const stat=data.adBrandStats.find(s=>s.gameId===id);
  if(!stat) return <p className="data-note">게임별 수집 광고 표본: 미수집</p>;
  return <details className="ad-game-evidence"><summary>{stat.name} 광고 근거 · AI 표본 {stat.classified}개 · 첫 3초 판독 10개</summary><p>조회 {stat.source.date}. 추정 광고비 ${stat.spendEstimate} · 기간·계산 방법 미확인.</p><Evidence source={stat.source} open={open}/>{data.adCreatives.filter(c=>c.gameId===id).map(c=><details key={c.adId}><summary>{c.actualType} · ID {c.adId}</summary><p>{c.description}</p><p>AI 라벨: {c.hook} · {c.format}. 첫 3초 화면 판독과 영상 전체 라벨의 범위가 다를 수 있습니다.</p><Evidence source={c.readingSource} open={open}/><a href={`https://www.facebook.com/ads/library/?id=${c.adId}`} target="_blank" rel="noreferrer">Meta 광고 원문</a></details>)}</details>;
}

export default function MarketingResearch({data,open}:{data:Dataset;open:OpenSource}) {
  const [weights,setWeights]=useResearchState(`${data.importedAt}/weights`,data.channelWeights.map(w=>String(w*100)));
  const [sampleMode,setSampleMode]=useResearchState(`${data.importedAt}/sampleMode`,'hook');
  const [dedupe,setDedupe]=useResearchState(`${data.importedAt}/dedupe`,false);
  const [gameId,setGameId]=useResearchState(`${data.importedAt}/adGame`,'all');
  const phases=data.marketingPlan.phases;
  const [budgets,setBudgets]=useResearchState(`${data.importedAt}/budgets`,phases.map(p=>String(p.budget)));
  const [cpis,setCpis]=useResearchState(`${data.importedAt}/cpis`,phases.map(p=>p.cpi===null?'':String(p.cpi)));
  const numericWeights=weights.map(w=>w.trim()?Number(w):NaN);
  const scores=data.advertisingChannels.map(c=>({channel:c,score:channelScore(c.scores,numericWeights)}));
  const validWeights=scores.every(s=>s.score!==null);
  const results=phases.map((p,i)=>planResult(p,budgets[i],cpis[i]));
  const validPlan=results.every(r=>r!==null);
  const total=results.reduce<{installs:number;d7:number}>((sum,r)=>({installs:sum.installs+(r?.installs||0),d7:sum.d7+(r?.d7||0)}),{installs:0,d7:0});
  const chosen=data.adBrandStats.filter(s=>gameId==='all'||s.gameId===gameId);
  const allCreatives=data.adCreatives.filter(c=>gameId==='all'||c.gameId===gameId);
  const uniqueCreatives=[...new Map(allCreatives.map(c=>[`${c.gameId}/${c.videoGroup}`,c])).values()];
  const sampleRows=dedupe?uniqueCreatives:allCreatives;
  const labels=sampleMode==='reading'?[...new Set(data.adCreatives.map(c=>c.actualType))]:[...new Set(data.adHookSamples.filter(s=>s.table===sampleMode).map(s=>s.label))];
  return <div className="marketing-research">
    <div className="section-title"><div><span className="section-index">ADVERTISING / SOURCE TABLES</span><h2>광고 채널과 수집 소재 비교</h2></div></div>
    <p className="data-note">이하 광고 채널 7개·게임 3개 표본과 실행안은 독립 조사 범위입니다. 상단 순위·검색 필터가 적용되지 않습니다. 기존 게임 전략의 소재 가설은 미검증 상태로 따로 표시합니다.</p>
    <div className="channel-panel"><h3>2인 팀 채널 평가</h3><p className="data-note">분석자 평가: 5개 축 각 1~5점(5가 좋음), 종합 0~100점. 실제 설치 성과·광고 효율이 아닙니다. Meta 두 채널과 Google Ads 앱 캠페인의 공개 성과 범위를 개별 채널 성과로 분리하지 않습니다.</p>
      <div className="local-controls weight-inputs">{data.channelAxes.map((axis,i)=><label key={axis}>{axis} (%)<input aria-label={`${axis} 가중치`} type="number" min="0" max="100" step="1" value={weights[i]} onChange={e=>setWeights(weights.map((w,j)=>j===i?e.target.value:w))}/></label>)}<button className="plain-button" onClick={()=>setWeights(data.channelWeights.map(w=>String(w*100)))}>가중치 원자료 기본값 복원</button></div>
      <p role="status" className={validWeights?'data-note':'input-error'}>가중치 합계 {numericWeights.every(Number.isFinite)?numericWeights.reduce((a,b)=>a+b,0):'입력 필요'}%{!validWeights?' · 모든 가중치는 0~100 사이이며 합계가 100%여야 계산합니다.':''}</p>
      {validWeights && <NumberBars rows={[...scores].sort((a,b)=>b.score!-a.score!).map(s=>({label:s.channel.name,value:s.score}))} max={100} unit="점"/>}
      <div className="table-scroll"><table className="analysis-table channel-heatmap"><thead><tr><th>채널</th>{data.channelAxes.map(a=><th key={a}>{a}</th>)}<th>판단 근거·공개 자료</th></tr></thead><tbody>{scores.map(({channel:c,score})=><tr key={c.name}><th>{c.name}<small>{score===null?'계산 보류':`${score.toFixed(1)} / 100점`}</small></th>{c.scores.map((s,i)=><td className="heat-cell" key={i} style={{background:`rgba(205,209,214,${s*.045})`}}>{s}/5</td>)}<td><details><summary>{c.reason.slice(0,60)}{c.reason.length>60?'…':''}</summary><p>{c.reason}</p><Evidence source={c.source} open={open}/><p>공개 도달: {c.public.reach} ({c.public.grade})</p><p>구매 도구: {c.public.buying}</p><p>{c.public.performance}</p><p>{c.public.genre}</p><p>비용: {c.public.cost}</p><p>{c.public.text}</p><Evidence source={c.public.source} open={open}/>{c.public.source.urls?.map(u=><a key={u} href={u} target="_blank" rel="noreferrer">외부 근거 열기</a>)}</details></td></tr>)}</tbody></table></div>
    </div>
    <div className="ad-sample-panel"><h3>AI 분류와 처음 3초 판독</h3><div className="local-controls"><label>게임<select aria-label="광고 표본 게임" value={gameId} onChange={e=>setGameId(e.target.value)}><option value="all">3개 게임 전체</option>{data.adBrandStats.map(s=><option value={s.gameId} key={s.gameId}>{s.name}</option>)}</select></label><label>표본 정의<select aria-label="광고 표본 정의" value={sampleMode} onChange={e=>setSampleMode(e.target.value)}><option value="hook">AI 후킹 유형 · 게임당 25개</option><option value="format">AI 영상 형식 · 게임당 25개</option><option value="reading">첫 3초 판독 · 게임당 10개</option></select></label>{sampleMode==='reading' && <label className="checkbox-label"><input aria-label="동일 영상 중복 제거" type="checkbox" checked={dedupe} onChange={e=>setDedupe(e.target.checked)}/>동일 영상 중복 제거</label>}</div>
      <p className="sample-denominator">AI 분류 표본 {chosen.length*25}개 · 광고 목록 {allCreatives.length}건 · 첫 3초 판독 {allCreatives.length}건 · 서로 다른 영상 {uniqueCreatives.length}개</p>
      <p className="data-note">조회 2026-10-05. AI 표본 25개와 판독 10개는 서로 다른 표본입니다. 다국어 광고를 포함하며 미국 전용 표본이 아닙니다. 집행 일수·소재 빈도는 전환율이나 효율을 의미하지 않습니다.</p>
      {chosen.map(stat=>{const values=labels.map(label=>({label,count:sampleMode==='reading'?sampleRows.filter(c=>c.gameId===stat.gameId&&c.actualType===label).length:data.adHookSamples.find(s=>s.gameId===stat.gameId&&s.table===sampleMode&&s.label===label)?.count||0}));const denominator=sampleMode==='reading'?sampleRows.filter(c=>c.gameId===stat.gameId).length:25;return <article className="sample-game" key={stat.gameId}><h4>{stat.name} <span>{denominator}개 기준</span></h4><div className="sample-stack" role="img" aria-label={values.map(v=>`${v.label} ${v.count}/${denominator}개`).join(', ')}>{values.filter(v=>v.count>0).map((v,i)=><span key={v.label} title={`${v.label}: ${v.count}개 (${(v.count/denominator*100).toFixed(1)}%)`} style={{width:`${v.count/denominator*100}%`,background:`hsl(215 10% ${75-i*9}%)`}}>{v.count}</span>)}</div><div className="sample-labels">{values.map(v=><span key={v.label}>{v.label} <strong>{v.count}개 · {(v.count/denominator*100).toFixed(1)}%</strong></span>)}</div><details><summary>광고 현황·표본 설명·근거</summary><p>집행 중 {stat.active.toLocaleString()}개 · 추적 {stat.tracked}개 · AI 분류 완료 {stat.classified}개 · 브랜드 현황 최장 {stat.longestDays}일</p><p>AdWhispr 추정 광고비 ${stat.spendEstimate}. {stat.note}</p>{stat.name==='MONOPOLY GO!' && <p>브랜드 현황은 203일, 영상 목록과 설명은 204일입니다. 출처 범위 차이 확인이 필요합니다.</p>}<Evidence source={stat.source} open={open}/>{sampleMode!=='reading' && data.adHookSamples.filter(s=>s.gameId===stat.gameId&&s.table===sampleMode).map(s=><p key={s.label}>{s.label} · {s.description}<Evidence source={s.source} open={open}/></p>)}</details></article>;})}
      <details><summary>영상 목록과 판독 원문 · {allCreatives.length}건</summary><div className="table-scroll"><table className="analysis-table creative-table"><thead><tr><th>게임·광고 ID</th><th>AI 분류·집행</th><th>처음 3초 판독</th><th>근거</th></tr></thead><tbody>{allCreatives.map(c=><tr key={c.adId}><th>{c.name}<a href={`https://www.facebook.com/ads/library/?id=${c.adId}`} target="_blank" rel="noreferrer">{c.adId}</a></th><td>{c.hook} · {c.format}<small>{c.days}일 · {c.tone} · {c.offer}</small><p>{c.copy}</p></td><td>{c.actualType}<small>요청 분류: {c.requestedType}</small><p>{c.description}</p><small>영상 묶음: {c.videoGroup}</small></td><td><Evidence source={c.source} open={open}/><Evidence source={c.readingSource} open={open}/></td></tr>)}</tbody></table></div></details>
    </div>
    <div className="plan-panel"><h3>단계별 마케팅 실행안</h3><p className="data-note">분석자 제안 · 계획 연결 후보 {data.marketingPlan.candidate}. {data.marketingPlan.summary}. 다른 후보의 CPI·예산·소재는 미작성입니다.</p><Evidence source={data.marketingPlan.source} open={open}/>
      <ol className="phase-timeline">{phases.map(p=><li key={p.name}><strong>{p.name}</strong><span>{p.timing}</span><small>{p.region} · {p.os||'해당 없음'}</small></li>)}</ol>
      <div className="table-scroll"><table className="analysis-table plan-table"><thead><tr><th>단계·채널</th><th>예산 (USD)</th><th>CPI (USD/설치)</th><th>참고 리텐션</th><th>예상 설치·D7</th><th>합격 기준·근거</th></tr></thead><tbody>{phases.map((p,i)=><tr key={p.name}><th>{p.name}<small>{p.region} · {p.channel}</small><small>{p.channelRank?'원자료 채널 순위 '+p.channelRank:''}</small></th><td><input aria-label={`${p.name} 예산`} type="number" min="0" step="100" value={budgets[i]} onChange={e=>setBudgets(budgets.map((b,j)=>j===i?e.target.value:b))}/></td><td>{p.cpi===null?'해당 없음':<><input aria-label={`${p.name} CPI`} type="number" min="0.001" step="0.01" value={cpis[i]} onChange={e=>setCpis(cpis.map((c,j)=>j===i?e.target.value:c))}/><small>{p.cpiId} · {p.cpiRegion} · {p.cpiPeriod}</small>{p.cpiSource && <Evidence source={p.cpiSource} open={open}/>}</>}</td><td>{p.d7Rate===null?'해당 없음':<>{p.retentionRegion} D7 P50<br/>{(p.d7Rate*100).toFixed(2)}%{p.retentionSource && <Evidence source={p.retentionSource} open={open}/>}</>}</td><td>{results[i]===null?<span className="input-error">예산·CPI 입력 확인</span>:<>{results[i]?.installs===null?'설치 해당 없음':`${Math.round(results[i]!.installs!).toLocaleString()}명 설치`}<br/>{results[i]?.d7===null?'D7 해당 없음':`D7 ${Math.round(results[i]!.d7!).toLocaleString()}명`}</>}</td><td><details><summary>{p.criterion}</summary><p>{p.reason}</p><Evidence source={p.source} open={open}/></details></td></tr>)}</tbody></table></div>
      <button className="plain-button" onClick={()=>{setBudgets(phases.map(p=>String(p.budget)));setCpis(phases.map(p=>p.cpi===null?'':String(p.cpi)));}}>예산·CPI 원자료 기본값 복원</button>
      <p className="plan-total" role="status">{validPlan?`예산 합계 $${budgets.reduce((a,b)=>a+Number(b),0).toLocaleString()} · 예상 설치 ${Math.round(total.installs).toLocaleString()}명 · 예상 D7 ${Math.round(total.d7).toLocaleString()}명`:'입력 오류가 있어 합계를 계산하지 않습니다.'}</p>
      <p className="data-note">예상 설치 = 예산 ÷ CPI. D7 = 예상 설치 × 지역 D7 P50. 소수 원값으로 계산 후 표시만 반올림합니다. 합계는 서로 다른 단계의 추정이며 같은 날짜 코호트가 아닙니다. 브라질에 남미 CPI, 인도네시아에 APAC CPI와 아시아 리텐션을 적용하는 가정입니다. APAC과 아시아의 지리 범위는 다릅니다. 로컬 입력은 원본 XLSX를 수정하지 않습니다.</p>
      {validPlan && <div className="small-multiples"><div><h4>예상 설치 (명)</h4><NumberBars rows={phases.map((p,i)=>({label:p.name,value:results[i]!.installs}))} max={Math.max(1,...results.map(r=>r?.installs||0))} unit="명"/></div><div><h4>예상 D7 잔존 (명)</h4><NumberBars rows={phases.map((p,i)=>({label:p.name,value:results[i]!.d7}))} max={Math.max(1,...results.map(r=>r?.d7||0))} unit="명"/></div></div>}
      <h4>광고 소재 A~E · 분석자 제안</h4>{data.marketingPlan.materials.map(m=><article className="material-row" key={m.name}><h4>{m.name}</h4><p>{m.opening}</p><p>{m.difficulty}</p><small>{m.reference}</small><Evidence source={m.source} open={open}/></article>)}
      <h4>측정 지표와 계획의 검증 기준</h4><div className="table-scroll"><table className="analysis-table"><thead><tr><th>지표</th><th>정의</th><th>비교 기준</th><th>근거</th></tr></thead><tbody>{data.marketingPlan.metrics.map(m=><tr key={m.name}><th>{m.name}</th><td>{m.meaning}</td><td>{m.criterion}</td><td>{m.reference}<Evidence source={m.source} open={open}/></td></tr>)}</tbody></table></div>
    </div>
  </div>;
}
