'use client';
import {useResearchState} from '@/lib/use-research-state';
import type {Dataset} from '@/lib/schema';
import {BenchmarkExplorer,Evidence,NumberBars,type OpenSource} from './analytics';
export default function MvpResearch({data,open}:{data:Dataset;open:OpenSource}) {
  const [decision,setDecision]=useResearchState(`${data.importedAt}/mvpDecision`,'all');
  const [candidate,setCandidate]=useResearchState(`${data.importedAt}/mvpCandidate`,data.mvpRecommended[0].gameId);
  const selected=data.mvpRecommended.find(c=>c.gameId===candidate)||data.mvpRecommended[0];
  const target=data.mvpTargets.find(c=>c.gameId===candidate);
  const rows=data.mvpAssessments.filter(r=>decision==='all'||r.decision===decision);
  return <div className="mvp-research"><h3>2인 개발 MVP 판단</h3><p className="data-note">세부 장르 구조를 평가한 분석자 점수입니다. 실제 개발비·기간·게임 매출 성과가 아닙니다. 원자료의 후보 판정(매출 Top 100 또는 다운로드만 높은 유형), 70점·50점 기준과 1점 항목 우선 규칙을 그대로 보존합니다.</p><div className="local-controls"><label>추천 후보<select aria-label="MVP 추천 후보" value={candidate} onChange={e=>setCandidate(e.target.value)}>{data.mvpRecommended.map(c=><option key={c.gameId} value={c.gameId}>{c.name}</option>)}</select></label></div><article className="candidate-detail"><h4>{selected.name} · {selected.score}/100 · {selected.decision}</h4><p>{selected.subgenre} · {selected.roles} · {selected.duration} (추정)</p><p>{selected.scope}</p><p>{selected.caution}</p><Evidence source={selected.source} open={open}/><p className="data-note">{candidate===data.mvpRecommended[0].gameId?'마케팅 실행안이 연결된 후보입니다.':'이 후보의 별도 마케팅 예산·CPI·소재 실행안은 미작성입니다.'}</p>{data.mvpSpecs.filter(s=>s.name===selected.name).map(s=><details key={s.name}><summary>MVP 명세 원문</summary><p>{s.values.filter(v=>v!==null).join(' · ')}</p><Evidence source={s.source} open={open}/></details>)}{target?<><h4>MVP 검증 참고값 · {target.region}</h4><NumberBars rows={(['d1','d7','d30'] as const).flatMap(k=>[{label:`${k.toUpperCase()} 지역 P50`,value:target[k].median*100},{label:`${k.toUpperCase()} 지역 P90 목표`,value:target[k].target*100}])} max={60} unit="%"/><p className="data-note">2026 보고서, 2025년 지역별 전 장르 자료. 합격선 선택과 P90 목표는 분석자 제안입니다. {(['d1','d7','d30'] as const).map(k=>`${k.toUpperCase()} 합격선 ${target[k].criterion}`).join(' · ')}</p><p>D90 글로벌 수익 참고: IAP ARPU ${target.iapArpu??'미수집'}, 광고 ARPU ${target.adArpu??'미수집'}, IAP ARPPU ${target.iapArppu??'미수집'}. ARPDAU는 미수집.</p><Evidence source={target.source} open={open}/></>:<p className="data-note">이 후보의 개별 MVP 검증 목표: 분석 미작성. 아래 공개 벤치마크를 참고할 수 있습니다.</p>}</article>
    <details><summary>전체 평가 목록 · {data.mvpAssessments.length}개 게임</summary><label>판정 필터<select aria-label="MVP 판정 필터" value={decision} onChange={e=>setDecision(e.target.value)}><option value="all">전체 판정</option>{[...new Set(data.mvpAssessments.map(a=>a.decision))].map(d=><option key={d}>{d}</option>)}</select></label><p className="data-note">현재 {rows.length}개 · 점수 작성 {rows.filter(r=>r.score!==null).length}개 · 점수 빈칸 {rows.filter(r=>r.score===null).length}개</p><div className="table-scroll"><table className="analysis-table"><thead><tr><th>게임</th><th>장르</th><th>후보·판정</th><th>평가점수 (0~100)</th><th>근거</th></tr></thead><tbody>{rows.map(r=><tr key={r.name}><th>{r.name}</th><td>{r.genre} · {r.subgenre}</td><td>{r.candidate} · {r.decision}</td><td>{r.score===null?<span>{r.scoreState==='intentionalBlank'?'후보 아님 · 의도적 빈 수식 결과':'평가 입력 부족 · 분석 미작성'}</span>:<div className="score-cell"><i style={{width:`${r.score}%`}}/><strong>{r.score}</strong></div>}</td><td><Evidence source={r.source} open={open}/></td></tr>)}</tbody></table></div></details>
    <details><summary>평가 항목·판단 근거 · 누락 평가 포함</summary><div className="table-scroll"><table className="analysis-table"><thead><tr><th>세부 장르</th><th>콘텐츠 / 서버 / 아트 / 운영 / 규제 (1~5)</th><th>점수·판정</th><th>판단 이유</th></tr></thead><tbody>{data.mvpCriteria.map(c=><tr key={`${c.genre}/${c.subgenre}`}><th>{c.genre} · {c.subgenre}</th><td>{c.scores.map(s=>s===null?'입력 부족':s).join(' / ')}</td><td>{c.score===null?'의도적 빈 수식 결과':c.score} · {c.decision}</td><td>{c.reason}<Evidence source={c.source} open={open}/></td></tr>)}</tbody></table></div></details>
    <BenchmarkExplorer data={data} open={open}/><aside className="method-note"><strong>반복 관측과 성장 추이</strong><p>현재 동일 국가·스토어·차트 조건의 반복 순위 관측이 없어 성장 추이는 미작성입니다. 수입기는 날짜별 추가 스냅샷을 보존하며 최신 기록과 개별 날짜를 선택할 수 있습니다. 서로 다른 국가 조사일이나 벤치마크 보고서 연도를 성장 추이로 연결하지 않습니다.</p></aside>
  </div>;
}
